library(lubridate)
#to read and subset data
house <- read.table(file = "household_power_consumption.txt",sep = ";",header = TRUE, na.strings = "?")
sub <- subset(house, Date == "1/2/2007" | Date == "2/2/2007")
sub$datetime <- dmy_hms(paste(sub$Date,sub$Time))
#to create plot
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(sub$datetime, sub$Global_active_power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(sub$datetime, sub$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(sub$datetime, sub$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(sub$datetime, sub$Sub_metering_2, type="l", col="red")
lines(sub$datetime, sub$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(sub$datetime, sub$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()